routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\crudController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

use App\Http\Controllers\ProductController;

Route::resource('data', crudController::class);
Route::put('/data/{id}', [DataDiriController::class, 'update'])->name('data.update');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Models/data_diri.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class data_diri extends Model
{
    use HasFactory;
    protected $fillable = [
        'Nama',
        'NIM',
        'Jenis_Kelamin',
        'Prodi',
        'Fakultas',
    ];
}

app/Models/identitas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class identitas extends Model
{
    use HasFactory;
    protected $fillable = [
        'Nama',
        'NIM',
        'Jenis_Kelamin',
        'Prodi',
        'Fakultas',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/crudController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\data_diri;
class crudController extends Controller
{
    public function index()
    {
        $datadiri = data_diri::all(); 
        return view('data', compact('datadiri'));
    }
    
    public function create()
    {
        return view('tambahdata');
    }
    
    //CRUD 
    //CREATE
    public function store(request $request){
        {
            $request->validate([
                'Nama' => 'required',
                'NIM' => 'required',
                'Jenis_Kelamin' => 'required',
                'Prodi' => 'required',
                'Fakultas' => 'required',
            ]);

            data_diri::create($request->all());
            return redirect()->route('data.index')->with('success','Product created successfully.');
            }
    }
     //READ
     public function show(data_diri $datadiri){
        return view('data',compact('datadiri'));
    }

    public function edit($id){
    $datadiri = data_diri::find($id);
    return view('edit', compact('datadiri'));
    }


    //UPDATE
    public function update($id, Request $request)
    {
        $request->validate([
            'Nama' => 'required',
            'NIM' => 'required',
            'Jenis_Kelamin' => 'required',
            'Prodi' => 'required',
            'Fakultas' => 'required',
        ]);

        $datadiri = data_diri::find($id);

        if(!$datadiri) {
            return redirect()->route('data.index')->with('error', 'Data not found');
        }

        $datadiri->update($request->all());

        return redirect()->route('data.index')->with('success', 'Data updated successfully');
    }
    //delete
    public function destroy($id)
    {
        $datadiri = data_diri::find($id);
        $datadiri->delete();
        return redirect()->route('data.index')->with('success','Product deleted successfully');
    }

}

resources/views/data.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Diri</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container" style="padding-top: 50px;" id="produklayanan">
    <h2 class="display-6 pb-3">Data Diri</h2>
    <a href="{{ route('data.create') }}" class="btn btn-primary mb-2">Tambah Data</a>
    <table class="table table-bordered">
        <thead>
            <tr class="text-center">
                <th scope="col">Nama</th>
                <th scope="col">NIM</th>
                <th scope="col">Jenis Kelamin</th>
                <th scope="col">Prodi</th>
                <th scope="col">Fakultas</th>
                <th scope="col">Aksi</th>
            </tr>
        </thead>
        <tbody>
            @forelse($datadiri as $s)
            <tr>
                <td>{{ $s->Nama }}</td>
                <td>{{ $s->NIM }}</td>
                <td>{{ $s->Jenis_Kelamin }}</td>
                <td>{{ $s->Prodi }}</td>
                <td>{{ $s->Fakultas }}</td>
                <td class="text-center">
                    <a href="/data/{{ $s->id }}/edit" class="btn btn-sm btn-primary">edit</a>
                    <form action="/data/{{ $s->id }}" method="POST" style="display:inline;">
                        @csrf
                        @method('DELETE')
                        <button type="submit" onclick="return confirm('Yakin ingin menghapus item');" class="btn btn-sm btn-danger"></i>delete</button>
                    </form>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="text-center">
                    <div class="alert alert-danger">
                        Data Data Diri belum tersedia.
                    </div>
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>

<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Data</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form action="{{ route('data.update', $datadiri->id) }}" method="POST">
                            @csrf
                            @method('PUT')

                            <div class="form-group">
                                <label for="Nama">Nama</label>
                                <input type="text" class="form-control" id="Nama" name="Nama" value="{{ $datadiri->Nama }}">
                            </div>

                            <div class="form-group">
                                <label for="NIM">NIM</label>
                                <input type="text" class="form-control" id="NIM" name="NIM" value="{{ $datadiri->NIM }}">
                            </div>

                            <div class="form-group">
                                <label for="Jenis_Kelamin">Jenis Kelamin</label>
                                <select class="form-control" id="Jenis_Kelamin" name="Jenis_Kelamin">
                                    <option value="Laki-laki" {{ $datadiri->Jenis_Kelamin == 'Laki-laki' ? 'selected' : '' }}>Laki-laki</option>
                                    <option value="Perempuan" {{ $datadiri->Jenis_Kelamin == 'Perempuan' ? 'selected' : '' }}>Perempuan</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="Prodi">Prodi</label>
                                <input type="text" class="form-control" id="Prodi" name="Prodi" value="{{ $datadiri->Prodi }}">
                            </div>

                            <div class="form-group">
                                <label for="Fakultas">Fakultas</label>
                                <input type="text" class="form-control" id="Fakultas" name="Fakultas" value="{{ $datadiri->Fakultas }}">
                            </div>

         

                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/tambahdata.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
 

    <div class="container">
        <h2>Tambah Data</h2>

        <form method="POST" action="{{ route('data.store') }}">
            @csrf
            <div class="form-group">
                <label for="nama">Nama:</label>
                <input type="text" class="form-control" id="nama" name="Nama" required>
            </div>
            <div class="form-group">
                <label for="nim">NIM:</label>
                <input type="text" class="form-control" id="nim" name="NIM" required>
            </div>
            <div class="form-group">
                <label for="jenis_kelamin">Jenis Kelamin:</label>
                <select class="form-control" id="jenis_kelamin" name="Jenis_Kelamin" required>
                    <option value="Laki-laki">Laki-laki</option>
                    <option value="Perempuan">Perempuan</option>
                </select>
            </div>
            <div class="form-group">
                <label for="prodi">Prodi:</label>
                <input type="text" class="form-control" id="prodi" name="Prodi" required>
            </div>
            <div class="form-group">
                <label for="fakultas">Fakultas:</label>
                <input type="text" class="form-control" id="fakultas" name="Fakultas" required>
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>